import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "wouter";
import { crm } from "@/lib/crm-api";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertTriangle, BarChart3, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Mail, Megaphone, MessageSquare, Pause, Plus, Send, ShieldCheck, Sparkles, Users } from "lucide-react";

const selectClass = "w-full rounded-md border border-input bg-background px-3 py-2 text-sm";
const fields = [
  ["customer_type","Customer type"],["lead_source","Lead source"],["lead_status","Lead status"],
  ["city","City"],["zip","ZIP code"],["tag","Customer tag"],["last_service_months","Months since last service"],
  ["equipment_type","Equipment type"],["equipment_brand","Equipment brand"],["equipment_age","Equipment age (years)"],
  ["quote_status","Quote status"],["invoice_status","Invoice status"],["membership_status","Membership status"],
  ["has_upcoming_job","Has upcoming job"],["lifetime_revenue","Lifetime revenue"],["has_email","Has email"],["has_phone","Has phone"],
];
const goals = [
  ["maintenance","Book seasonal maintenance"],["sale","Promote a sale"],["unsold_estimate","Follow up on unsold estimates"],
  ["inactive_customer","Bring back inactive customers"],["equipment_replacement","Follow up on aging equipment"],
  ["membership","Promote Crown Care"],["referral","Referral or coupon outreach"],["custom","Custom campaign"],
];
const pretty = (s:string) => s.replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
const money = (cents:number) => new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format((cents||0)/100);
const statusTone = (s:string) => ["active","completed","sent","delivered"].includes(s) ? "bg-green-100 text-green-800" : ["failed","stopped"].includes(s) ? "bg-red-100 text-red-800" : ["paused"].includes(s) ? "bg-amber-100 text-amber-800" : "bg-sky-100 text-sky-800";

function Notice({children}:{children:string}) { return children ? <p role="status" className="rounded-lg border bg-muted/40 p-3 text-sm">{children}</p> : null; }
function Empty({title,body,action}:{title:string;body:string;action?:React.ReactNode}) { return <Card><CardContent className="p-8 text-center space-y-3"><div className="mx-auto flex h-11 w-11 items-center justify-center rounded-full bg-sky-100 text-sky-700"><Sparkles size={20}/></div><h3 className="font-semibold">{title}</h3><p className="text-sm text-muted-foreground max-w-xl mx-auto">{body}</p>{action}</CardContent></Card>; }

function ConditionRows({value,onChange}:{value:any[];onChange:(v:any[])=>void}) {
  return <div className="space-y-2">
    {value.map((c,i)=><div key={i} className="grid gap-2 sm:grid-cols-[1.5fr_1fr_1.3fr_auto]">
      <select className={selectClass} value={c.field} onChange={e=>onChange(value.map((x,j)=>j===i?{...x,field:e.target.value}:x))}>{fields.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select>
      <select className={selectClass} value={c.op} onChange={e=>onChange(value.map((x,j)=>j===i?{...x,op:e.target.value}:x))}><option value="eq">is</option><option value="neq">is not</option><option value="contains">contains</option><option value="gt">greater than</option><option value="lt">less than</option><option value="exists">is present</option></select>
      {c.op === "exists" ? <select className={selectClass} value={String(c.value)} onChange={e=>onChange(value.map((x,j)=>j===i?{...x,value:e.target.value==="true"}:x))}><option value="true">Yes</option><option value="false">No</option></select> : <Input value={c.value ?? ""} placeholder="Value" onChange={e=>onChange(value.map((x,j)=>j===i?{...x,value:e.target.value}:x))}/>} 
      <Button variant="ghost" onClick={()=>onChange(value.filter((_,j)=>j!==i))}>Remove</Button>
    </div>)}
    <Button size="sm" variant="outline" onClick={()=>onChange([...value,{field:"last_service_months",op:"gt",value:"12"}])}><Plus size={14} className="mr-1"/>Add filter</Button>
  </div>;
}

function AudienceDialog({open,onOpenChange,onSaved}:{open:boolean;onOpenChange:(v:boolean)=>void;onSaved:()=>void}) {
  const [form,setForm]=useState<any>({name:"",description:"",mode:"dynamic",filters:[],exclusions:[],active:true,archived:false});
  const [preview,setPreview]=useState<any>(null); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState("");
  const runPreview=async()=>{setBusy(true);try{setPreview(await crm("crm/marketing/audiences/preview","POST",form));setNotice("");}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  const save=async()=>{setBusy(true);try{await crm("crm/marketing/audiences","POST",form);onSaved();onOpenChange(false);setForm({name:"",description:"",mode:"dynamic",filters:[],exclusions:[],active:true,archived:false});}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Create an audience</DialogTitle><DialogDescription>Choose which Air King customers should qualify. Permission and suppression rules are always checked separately.</DialogDescription></DialogHeader>
    <Notice>{notice}</Notice><div className="grid sm:grid-cols-2 gap-4"><div><Label>Name</Label><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Customers due for AC maintenance"/></div><div><Label>Audience type</Label><select className={selectClass} value={form.mode} onChange={e=>setForm({...form,mode:e.target.value})}><option value="dynamic">Dynamic — updates each run</option><option value="static">Static — freeze at launch</option></select></div></div><div><Label>Description</Label><Textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div>
    <section className="space-y-2"><h3 className="font-semibold">Customers must match all of these</h3><ConditionRows value={form.filters} onChange={filters=>setForm({...form,filters})}/></section>
    <section className="space-y-2"><h3 className="font-semibold">Exclude customers matching any of these</h3><ConditionRows value={form.exclusions} onChange={exclusions=>setForm({...form,exclusions})}/></section>
    {preview&&<div className="rounded-xl border bg-sky-50 p-4"><p className="font-semibold">{preview.total} customers checked</p><p className="text-sm text-muted-foreground">{preview.eligible_email} eligible for marketing email · {preview.eligible_sms} eligible for marketing text</p><div className="mt-3 max-h-44 overflow-y-auto divide-y">{preview.rows.slice(0,50).map((r:any)=><div key={r.customer_id} className="py-2 text-sm flex justify-between gap-3"><span>{r.name}</span><span className="text-muted-foreground text-right">{!r.eligibility.email?"Email ready":r.eligibility.email}</span></div>)}</div></div>}
    <div className="flex justify-between"><Button variant="outline" disabled={busy} onClick={runPreview}>Preview customers</Button><Button disabled={busy||!form.name} onClick={save}>Save Audience</Button></div>
  </DialogContent></Dialog>;
}

function CampaignDialog({open,onOpenChange,audiences,templates,onSaved}:{open:boolean;onOpenChange:(v:boolean)=>void;audiences:any[];templates:any[];onSaved:()=>void}) {
  const [page,setPage]=useState(1); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState("");
  const [form,setForm]=useState<any>({name:"",description:"",goal:"maintenance",campaign_type:"one_time",audience_id:"",channels:["email"],starts_at:null,recurrence:{},settings:{frequency_days:7,max_contacts:2,large_send_threshold:250,stop_on_booking:true},steps:[{action:"email",template_id:"",delay_minutes:0,conditions:[]}]});
  const marketingTemplates=templates.filter((x:any)=>x.category==="marketing"&&x.active&&!x.archived);
  const makeStep=(channel:string)=>{const t=marketingTemplates.find((x:any)=>x.channel===channel);return {action:channel,template_id:t?.id||"",subject:t?.subject||"",body:t?.body||"",delay_minutes:0,conditions:[]}};
  const syncSteps=(channels:string[])=>setForm({...form,channels,steps:form.steps.filter((s:any)=>channels.includes(s.action)).concat(channels.filter((c:string)=>!form.steps.some((s:any)=>s.action===c)).map(makeStep))});
  const save=async()=>{setBusy(true);try{await crm("crm/marketing/campaigns","POST",form);onSaved();onOpenChange(false);setPage(1);setNotice("");}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  const eligible=page===1?!!form.name:page===2?!!form.audience_id:page===3?form.steps.every((s:any)=>s.template_id):true;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-4xl max-h-[92vh] overflow-y-auto"><DialogHeader><DialogTitle>Create Campaign</DialogTitle><DialogDescription>Step {page} of 5 · Goal → Audience → Message → Timing → Review</DialogDescription></DialogHeader><div className="grid grid-cols-5 gap-1">{[1,2,3,4,5].map(n=><div key={n} className={`h-1.5 rounded-full ${n<=page?"bg-sky-600":"bg-muted"}`}/>)}</div><Notice>{notice}</Notice>
    {page===1&&<div className="space-y-4"><div><Label>Campaign name</Label><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Fall furnace tune-up 2026"/></div><div><Label>What do you want to accomplish?</Label><div className="grid sm:grid-cols-2 gap-2 mt-2">{goals.map(([v,l])=><button key={v} onClick={()=>setForm({...form,goal:v})} className={`rounded-lg border p-3 text-left text-sm ${form.goal===v?"border-sky-600 bg-sky-50":"hover:bg-muted"}`}><span className="font-medium">{l}</span></button>)}</div></div><div><Label>Description</Label><Textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Internal note about this campaign"/></div></div>}
    {page===2&&<div className="space-y-3"><h3 className="font-semibold">Who should receive it?</h3>{!audiences.length?<p className="text-sm text-muted-foreground">Create an audience first, then return to this campaign.</p>:audiences.map(a=><button key={a.id} onClick={()=>setForm({...form,audience_id:a.id})} className={`w-full rounded-lg border p-4 text-left ${form.audience_id===a.id?"border-sky-600 bg-sky-50":"hover:bg-muted"}`}><div className="flex justify-between"><span className="font-medium">{a.name}</span><Badge variant="secondary">{a.estimated_count||0} reachable</Badge></div><p className="text-sm text-muted-foreground mt-1">{a.description||"Saved Air King audience"}</p></button>)}</div>}
    {page===3&&<div className="space-y-5"><div><Label>Channels</Label><div className="flex gap-3 mt-2">{["email","sms"].map(channel=>{const selected=form.channels.includes(channel);return <button key={channel} onClick={()=>{const next=selected?form.channels.filter((x:string)=>x!==channel):[...form.channels,channel];if(next.length)syncSteps(next)}} className={`rounded-lg border px-4 py-3 text-sm ${selected?"border-sky-600 bg-sky-50":""}`}>{channel==="email"?<Mail className="inline mr-2" size={16}/>:<MessageSquare className="inline mr-2" size={16}/>} {pretty(channel)}</button>})}</div></div>{form.steps.map((step:any,i:number)=><div key={i} className="rounded-lg border p-4 space-y-3"><div className="flex justify-between"><h4 className="font-medium">Step {i+1}: {step.action==="email"?"Email":"Text message"}</h4>{form.steps.length>1&&<Button type="button" size="sm" variant="ghost" onClick={()=>setForm({...form,steps:form.steps.filter((_:any,j:number)=>j!==i)})}>Remove</Button>}</div><select className={selectClass} value={step.template_id||""} onChange={e=>{const t=marketingTemplates.find((x:any)=>x.id===e.target.value);setForm({...form,steps:form.steps.map((x:any,j:number)=>j===i?{...x,template_id:e.target.value,subject:t?.subject||"",body:t?.body||""}:x)})}}><option value="">Choose a marketing template</option>{marketingTemplates.filter((t:any)=>t.channel===step.action).map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select>{step.action==="email"&&<div><Label>Subject</Label><Input value={step.subject||""} onChange={e=>setForm({...form,steps:form.steps.map((x:any,j:number)=>j===i?{...x,subject:e.target.value}:x)})}/></div>}<div><Label>Message</Label><Textarea rows={5} value={step.body||""} onChange={e=>setForm({...form,steps:form.steps.map((x:any,j:number)=>j===i?{...x,body:e.target.value}:x)})}/></div><div className="max-w-xs"><Label>Wait after previous step (minutes)</Label><Input type="number" min={0} value={step.delay_minutes} onChange={e=>setForm({...form,steps:form.steps.map((x:any,j:number)=>j===i?{...x,delay_minutes:Number(e.target.value)}:x)})}/></div><p className="text-xs text-muted-foreground">The exact subject and message saved here are frozen for the campaign history.</p></div>)}<div className="flex gap-2"><Button type="button" variant="outline" onClick={()=>setForm({...form,channels:Array.from(new Set([...form.channels,"email"])),steps:[...form.steps,makeStep("email")]})}><Mail size={15} className="mr-1"/>Add Email Step</Button><Button type="button" variant="outline" onClick={()=>setForm({...form,channels:Array.from(new Set([...form.channels,"sms"])),steps:[...form.steps,makeStep("sms")]})}><MessageSquare size={15} className="mr-1"/>Add Text Step</Button></div></div>}
    {page===4&&<div className="space-y-4"><div><Label>Campaign type</Label><select className={selectClass} value={form.campaign_type} onChange={e=>setForm({...form,campaign_type:e.target.value})}><option value="one_time">Send one time</option><option value="scheduled">Schedule for later</option><option value="sequence">Multi-step sequence</option><option value="recurring">Recurring audience campaign</option></select></div>{form.campaign_type!=="one_time"&&<div><Label>First send</Label><Input type="datetime-local" onChange={e=>setForm({...form,starts_at:e.target.value?new Date(e.target.value).toISOString():null})}/></div>}{form.campaign_type==="recurring"&&<div className="max-w-xs"><Label>Repeat every (days)</Label><Input type="number" min={7} value={form.recurrence.every_days||30} onChange={e=>setForm({...form,recurrence:{every_days:Number(e.target.value)}})}/></div>}<div className="grid sm:grid-cols-2 gap-3"><div><Label>Frequency period (days)</Label><Input type="number" value={form.settings.frequency_days} onChange={e=>setForm({...form,settings:{...form.settings,frequency_days:Number(e.target.value)}})}/></div><div><Label>Max contacts in period</Label><Input type="number" value={form.settings.max_contacts} onChange={e=>setForm({...form,settings:{...form.settings,max_contacts:Number(e.target.value)}})}/></div></div><label className="flex items-center justify-between rounded-lg border p-3 text-sm"><span><strong>Stop after booking</strong><br/><span className="text-muted-foreground">Cancel pending steps when this customer already has an upcoming job.</span></span><Switch checked={form.settings.stop_on_booking} onCheckedChange={v=>setForm({...form,settings:{...form.settings,stop_on_booking:v}})}/></label></div>}
    {page===5&&<div className="space-y-4"><div className="rounded-xl border bg-sky-50 p-5"><h3 className="font-semibold text-lg">{form.name}</h3><p className="text-sm text-muted-foreground">{goals.find(x=>x[0]===form.goal)?.[1]} · {pretty(form.campaign_type)}</p><div className="grid sm:grid-cols-3 gap-3 mt-4 text-sm"><div><span className="text-muted-foreground">Audience</span><p className="font-medium">{audiences.find(a=>a.id===form.audience_id)?.name}</p></div><div><span className="text-muted-foreground">Channels</span><p className="font-medium">{form.channels.map(pretty).join(" + ")}</p></div><div><span className="text-muted-foreground">Safety</span><p className="font-medium">Consent + frequency rechecked</p></div></div></div><div className="rounded-lg border p-4"><div className="flex gap-2"><ShieldCheck className="text-green-700"/><div><p className="font-medium">This saves as a draft</p><p className="text-sm text-muted-foreground">Nothing is sent until an owner or administrator launches it. Launch performs provider and sending-safety checks again.</p></div></div></div></div>}
    <div className="flex justify-between pt-2"><Button variant="outline" disabled={page===1||busy} onClick={()=>setPage(page-1)}><ChevronLeft size={16} className="mr-1"/>Back</Button>{page<5?<Button disabled={!eligible} onClick={()=>setPage(page+1)}>Continue<ChevronRight size={16} className="ml-1"/></Button>:<Button disabled={busy} onClick={save}>Save Draft</Button>}</div>
  </DialogContent></Dialog>;
}

export default function Marketing() {
  const [audienceOpen,setAudienceOpen]=useState(false); const [campaignOpen,setCampaignOpen]=useState(false); const [notice,setNotice]=useState(""); const [launchReview,setLaunchReview]=useState<any>(null); const [launchName,setLaunchName]=useState(""); const [busy,setBusy]=useState(false);
  const {data,refetch,error}=useQuery({queryKey:["marketing"],queryFn:()=>crm("crm/marketing"),refetchInterval:30000});
  const {data:templates=[]}=useQuery({queryKey:["templates"],queryFn:()=>crm("crm/templates")});
  const {data:config}=useQuery({queryKey:["crm-config"],queryFn:()=>crm("crm/config")});
  const campaigns=data?.campaigns||[], audiences=data?.audiences||[], summary=data?.summary||{};
  const canEdit=["owner","admin"].includes(config?.role);
  const messageCounts=useMemo(()=>({email:campaigns.filter((x:any)=>x.channels?.includes("email")).length,sms:campaigns.filter((x:any)=>x.channels?.includes("sms")).length}),[campaigns]);
  const reviewLaunch=async(campaign:any)=>{setBusy(true);try{const preview=await crm(`crm/marketing/campaigns/${campaign.id}/preview`,"POST",{});setLaunchName("");setLaunchReview({...preview,campaign})}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  const launch=async()=>{if(!launchReview)return;setBusy(true);try{const {campaign,revision,eligible_count}=launchReview;const r=await crm(`crm/marketing/campaigns/${campaign.id}/launch`,"POST",{revision,confirm_count:eligible_count,confirm_name:launchName},crypto.randomUUID());setNotice(r.message);setLaunchReview(null);refetch()}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
  const toggle=async(id:string,enabled:boolean)=>{try{const r=await crm(`crm/marketing/campaigns/${id}/toggle`,"POST",{enabled});setNotice(r.message);refetch()}catch(e:any){setNotice(e.message)}};
  return <div className="p-4 sm:p-6 max-w-7xl mx-auto space-y-6"><header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold flex items-center gap-2"><Megaphone className="text-sky-700"/>Marketing</h1><p className="text-sm text-muted-foreground">Reach the right customers, book more work, and see what produced revenue.</p></div>{canEdit&&<div className="flex gap-2"><Button variant="outline" onClick={()=>setAudienceOpen(true)}><Users size={16} className="mr-2"/>New Audience</Button><Button onClick={()=>setCampaignOpen(true)}><Plus size={16} className="mr-2"/>Create Campaign</Button></div>}</header><Notice>{notice||error?.message||""}</Notice>
    {!data?.release_ready&&<div className="rounded-lg border border-amber-300 bg-amber-50 p-4 text-sm"><strong>Campaign sending is locked.</strong> You can safely build audiences, templates, and drafts. Complete the launch checklist before enabling mass sends.</div>}
    <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{[["Active campaigns",summary.active||0,Send],["Messages delivered",summary.delivered||0,CheckCircle2],["Completed revenue",money(summary.completed_revenue_cents||0),BarChart3],["Needs attention",summary.failed||0,AlertTriangle]].map(([label,value,Icon]:any)=><Card key={label}><CardContent className="p-4 flex items-center justify-between"><div><p className="text-xs text-muted-foreground">{label}</p><p className="text-2xl font-bold mt-1">{value}</p></div><Icon className="text-sky-700" size={22}/></CardContent></Card>)}</div>
    <Tabs defaultValue="overview"><TabsList className="w-full justify-start overflow-x-auto h-auto"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="campaigns">Campaigns</TabsTrigger><TabsTrigger value="audiences">Audiences</TabsTrigger><TabsTrigger value="templates">Templates</TabsTrigger><TabsTrigger value="results">Results</TabsTrigger><TabsTrigger value="health">Consent & Health</TabsTrigger></TabsList>
      <TabsContent value="overview" className="space-y-5"><Card><CardHeader><CardTitle>Quick starts for Air King</CardTitle></CardHeader><CardContent className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{[["Spring AC tune-up","Cooling equipment with maintenance due"],["Fall furnace tune-up","Heating equipment before cold weather"],["Unsold estimate","Quotes still pending after follow-up"],["Aging equipment","Systems ready for replacement discussion"],["Inactive customer","No completed service in 12 months"],["Custom sale","Your offer, dates, audience, and message"]].map(([title,body])=><button key={title} disabled={!canEdit} onClick={()=>setCampaignOpen(true)} className="rounded-lg border p-4 text-left hover:border-sky-500 hover:bg-sky-50"><p className="font-medium">{title}</p><p className="text-sm text-muted-foreground mt-1">{body}</p></button>)}</CardContent></Card><Card><CardHeader><CardTitle>Current work</CardTitle></CardHeader><CardContent>{campaigns.length?<div className="divide-y">{campaigns.slice(0,5).map((c:any)=><div key={c.id} className="py-3 flex items-center justify-between gap-3"><div><p className="font-medium">{c.name}</p><p className="text-xs text-muted-foreground">{c.channels.map(pretty).join(" + ")} · {pretty(c.goal)}</p></div><Badge className={statusTone(c.status)}>{pretty(c.status)}</Badge></div>)}</div>:<p className="text-sm text-muted-foreground">No campaigns yet. Start with a seasonal maintenance campaign.</p>}</CardContent></Card></TabsContent>
      <TabsContent value="campaigns" className="space-y-3">{!campaigns.length?<Empty title="Create your first Air King campaign" body="Build a draft, preview the audience, and launch only when you are ready." action={canEdit?<Button onClick={()=>setCampaignOpen(true)}>Create Campaign</Button>:undefined}/>:campaigns.map((c:any)=><Card key={c.id}><CardContent className="p-5 flex flex-wrap items-center justify-between gap-4"><div><div className="flex gap-2 items-center"><h3 className="font-semibold">{c.name}</h3><Badge className={statusTone(c.status)}>{pretty(c.status)}</Badge></div><p className="text-sm text-muted-foreground mt-1">{pretty(c.goal)} · {c.channels.map(pretty).join(" + ")} · {audiences.find((a:any)=>a.id===c.audience_id)?.name||"Audience"}</p></div>{canEdit&&<div className="flex gap-2">{c.status==="draft"&&<Button size="sm" disabled={busy||!data?.release_ready} onClick={()=>reviewLaunch(c)}><Send size={14} className="mr-1"/>Review & Launch</Button>}{c.enabled&&<Button size="sm" variant="outline" onClick={()=>toggle(c.id,false)}><Pause size={14} className="mr-1"/>Pause</Button>}{c.status==="paused"&&<Button size="sm" onClick={()=>toggle(c.id,true)}>Resume</Button>}</div>}</CardContent></Card>)}</TabsContent>
      <TabsContent value="audiences" className="space-y-3">{!audiences.length?<Empty title="Build a reusable audience" body="Examples include customers due for maintenance, aging systems, inactive customers, or pending estimates." action={canEdit?<Button onClick={()=>setAudienceOpen(true)}>New Audience</Button>:undefined}/>:<div className="grid md:grid-cols-2 gap-3">{audiences.map((a:any)=><Card key={a.id}><CardContent className="p-5"><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{a.name}</h3><p className="text-sm text-muted-foreground mt-1">{a.description}</p></div><Badge variant="secondary">{a.estimated_count||0}</Badge></div><p className="text-xs text-muted-foreground mt-4">{pretty(a.mode)} · {(a.filters||[]).length} filters · {(a.exclusions||[]).length} exclusions</p></CardContent></Card>)}</div>}</TabsContent>
      <TabsContent value="templates"><Card><CardContent className="p-6 flex flex-wrap justify-between gap-4"><div><h3 className="font-semibold">Marketing email and text templates</h3><p className="text-sm text-muted-foreground mt-1">Create branded messages, insert customer details, preview, duplicate, and archive.</p></div><Link href="/templates"><Button variant="outline">Open Templates</Button></Link></CardContent></Card></TabsContent>
      <TabsContent value="results"><Card><CardHeader><CardTitle>Campaign results</CardTitle></CardHeader><CardContent>{campaigns.length?<div className="divide-y">{campaigns.map((c:any)=><div key={c.id} className="grid grid-cols-2 sm:grid-cols-5 gap-2 py-3 text-sm"><span className="font-medium col-span-2">{c.name}</span><span>{pretty(c.status)}</span><span>{c.channels.join(" + ")}</span><span>{c.updated_at?new Date(c.updated_at).toLocaleDateString():"—"}</span></div>)}</div>:<p className="text-sm text-muted-foreground">Delivery, click, booking, and revenue results will appear after a campaign is launched.</p>}</CardContent></Card></TabsContent>
      <TabsContent value="health" className="grid md:grid-cols-2 gap-4"><Card><CardHeader><CardTitle>Sending readiness</CardTitle></CardHeader><CardContent className="space-y-3">{[["Resend email",config?.connections?.email],["Email webhook",config?.connections?.email_webhook],["Twilio texting",config?.connections?.twilio],["Secure unsubscribe",config?.connections?.unsubscribe],["Business mailing address",config?.connections?.marketing_address],["Background worker",config?.connections?.worker],["Customer sending",config?.settings?.sending_enabled],["Marketing sending",config?.connections?.marketing]].map(([label,ok]:any)=><div key={label} className="flex justify-between text-sm"><span>{label}</span><Badge className={ok?"bg-green-100 text-green-800":"bg-amber-100 text-amber-800"}>{ok?"Ready":"Setup required"}</Badge></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Safety defaults</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p className="flex gap-2"><ShieldCheck size={18} className="text-green-700"/>Marketing and transactional permissions stay separate.</p><p className="flex gap-2"><Clock3 size={18} className="text-sky-700"/>Texts wait for {config?.settings?.sms_start??8}:00–{config?.settings?.sms_end??19}:00 in {config?.settings?.timezone||"Air King time"}.</p><p className="flex gap-2"><Users size={18} className="text-sky-700"/>Every recipient is checked again immediately before sending.</p><p className="text-muted-foreground">Email campaigns: {messageCounts.email} · Text campaigns: {messageCounts.sms}</p></CardContent></Card></TabsContent>
    </Tabs><AudienceDialog open={audienceOpen} onOpenChange={setAudienceOpen} onSaved={refetch}/><CampaignDialog open={campaignOpen} onOpenChange={setCampaignOpen} audiences={audiences} templates={templates} onSaved={refetch}/><Dialog open={!!launchReview} onOpenChange={v=>!v&&setLaunchReview(null)}><DialogContent><DialogHeader><DialogTitle>Confirm campaign launch</DialogTitle><DialogDescription>This is the final check before customer messages are queued.</DialogDescription></DialogHeader>{launchReview&&<div className="space-y-4"><div className="rounded-lg bg-sky-50 p-4"><p className="font-semibold">{launchReview.campaign.name}</p><p className="text-sm mt-1">{launchReview.eligible_count} customers currently have at least one eligible channel.</p><p className="text-xs text-muted-foreground mt-2">{launchReview.people.length-launchReview.eligible_count} customers are excluded by audience, contact, consent, suppression, or duplicate-destination checks.</p></div><div><Label>Type the campaign name to confirm</Label><Input value={launchName} onChange={e=>setLaunchName(e.target.value)} placeholder={launchReview.campaign.name}/></div><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setLaunchReview(null)}>Cancel</Button><Button disabled={busy||launchName!==launchReview.campaign.name} onClick={launch}>Confirm & Launch</Button></div></div>}</DialogContent></Dialog></div>;
}
