import { z } from "zod";
export const results = ["OK", "Attention", "Unsafe", "N/A", "Not tested"] as const;
const common = ["Ask about comfort, noise, odors and previous problems", "Check thermostat, fault history and operating sequence", "Inspect filter fit; clean or replace per coverage and approval", "Inspect blower, cabinet and accessible air paths", "Inspect wiring, connections and electrical components"];
export const templates = {
 furnace: {title:"Furnace",scope:"Natural gas / propane furnace. Use the exact model manual; electric heat and heat pumps require separate procedures.",tasks:[...common,"Check gas connections for leaks using approved methods","Inspect venting, combustion air and terminations","Inspect accessible heat exchanger; record method and limitations","Inspect/service burners, ignition and flame sensor per manufacturer","For condensing units, service trap, drain and pump as applicable","Check safety controls using manufacturer procedures","Run applicable stages; verify start, operation and shutdown"],readings:["Return temperature (°F)","Supply temperature (°F)","Temperature rise target range (°F)","Return static, signed (in. w.c.)","Supply static, signed (in. w.c.)","Total external static (in. w.c.)","Maximum rated external static (in. w.c.)","Line voltage (V)","Blower current (A)","Inducer current (A)","Inlet gas pressure under load (in. w.c.)","Manifold gas pressure (in. w.c.)","Flame signal (µA DC)","Ambient CO (ppm) / location / time","Flue CO measured (ppm)","Flue CO air-free (ppm)","Oxygen (%)","Flue temperature (°F)","Draft / vent pressure (in. w.c.)"]},
 ac:{title:"AC",scope:"Ducted split-system cooling. Identify refrigerant and follow model-specific procedures, including A2L precautions when applicable.",tasks:[...common,"Inspect indoor coil; record access and cleaning needed","Inspect/clean outdoor coil with manufacturer-approved methods","Check fan blade, motor, mounts and outdoor clearance","Test applicable capacitors against rated values and tolerance","Inspect pan/drain; verify drainage and float/pump operation","Inspect refrigerant piping, insulation and signs of leakage","Run cooling; verify stable operation and proper shutdown"],readings:["Refrigerant type / metering device","Return temperature (°F)","Supply temperature (°F)","Outdoor dry bulb (°F)","Return wet bulb (°F) or relative humidity (%)","Return static, signed (in. w.c.)","Supply static, signed (in. w.c.)","Total external static (in. w.c.)","Maximum rated external static (in. w.c.)","Airflow method / measured result / target","Supply voltage (V)","Compressor current (A)","Outdoor fan current (A)","Indoor blower current (A)","Capacitor HERM rated / measured (µF) / tolerance","Capacitor FAN rated / measured (µF) / tolerance","Suction pressure (psig)","Liquid pressure (psig)","Suction line temperature (°F)","Liquid line temperature (°F)","Superheat actual / target (°F)","Subcooling actual / target (°F)"]}
};
const answer=z.object({result:z.enum(results).optional(),note:z.string().max(1500)}).strict();
export const checklistSchema=z.object({id:z.string().uuid(),kind:z.enum(["furnace","ac"]),equipmentId:z.string().min(1).max(200),unit:z.number().int().min(1).max(100),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v,"Choose a valid visit date."),technician:z.string().trim().max(160),equipmentLabel:z.string().max(500),modelSerial:z.string().max(500),filter:z.string().max(500),stage:z.string().max(200),manual:z.string().max(500),answers:z.record(z.string(),answer),readings:z.record(z.string(),z.string().max(500)),work:z.string().max(4000),followUp:z.string().max(4000),finalCondition:z.enum(["","Operating","Needs attention","Shut down"]),restored:z.boolean(),status:z.enum(["draft","completed"])}).strict();
export type Checklist=z.infer<typeof checklistSchema>;
export function completionErrors(c:Checklist){
 const t=templates[c.kind], errors:string[]=[];
 if(!c.technician.trim())errors.push("Enter the technician name.");
 if(!c.modelSerial.trim()||!c.manual.trim()||!c.stage.trim())errors.push("Enter model/serial, manual reference and tested stage or speed.");
 t.tasks.forEach((_,i)=>{const a=c.answers[String(i)];if(!a?.result)errors.push(`Choose a result for inspection ${i+1}.`);else if(a.result!=="OK"&&!a.note.trim())errors.push(`Explain inspection ${i+1}.`);});
 t.readings.forEach(label=>{const v=c.readings[label]?.trim()||"";if(!v)errors.push(`Enter ${label}, or N/A / not tested with a reason.`);else if(/^(n\/?a|not tested)\s*$/i.test(v))errors.push(`Explain why ${label} is not applicable or not tested.`);});
 if(!c.work.trim())errors.push("Describe the work performed.");
 if(!c.finalCondition)errors.push("Choose the final operating condition.");
 if(!c.restored)errors.push("Confirm panels, thermostat and work area were addressed.");
 if(Object.values(c.answers).some(a=>a.result&&a.result!=="OK"&&a.result!=="N/A")&&!c.followUp.trim())errors.push("Record customer notification and follow-up for outstanding findings.");
 if(Object.values(c.answers).some(a=>a.result==="Unsafe")&&c.finalCondition==="Operating")errors.push("Resolve unsafe results or record Needs attention / Shut down with the action taken.");
 return errors;
}
