// Generates an idempotent Supabase SQL file (schema + RLS + seed data)
// from the existing mock-data.ts. Run: npx tsx scripts/generate-supabase-sql.ts
import {
  customers,
  quotes,
  workOrders,
  invoices,
  memberships,
} from "../client/src/data/mock-data";

// Escape a JS object into a SQL jsonb string literal (single quotes doubled)
function jsonb(obj: unknown): string {
  const json = JSON.stringify(obj);
  // double single quotes for SQL string safety
  return `'${json.replace(/'/g, "''")}'::jsonb`;
}

function sqlStr(s: string): string {
  return `'${String(s).replace(/'/g, "''")}'`;
}

const lines: string[] = [];
const out = (s = "") => lines.push(s);

out("-- ============================================================");
out("-- Air King CRM — Supabase schema + seed (Phase 1)");
out("-- Generated by scripts/generate-supabase-sql.ts");
out("-- Idempotent: safe to re-run. Uses ON CONFLICT (id) DO UPDATE.");
out("-- WARNING: RLS policies below are PERMISSIVE for the Phase 1");
out("-- staging/demo phase (synthetic test data only). They MUST be");
out("-- replaced with authenticated, per-user policies in Phase 2");
out("-- (Supabase Auth) BEFORE any real customer data is entered.");
out("-- ============================================================");
out();

out("-- ---------- TABLES ----------");
out();
out("create table if not exists customers (");
out("  id text primary key,");
out("  company_id text not null default 'air-king',");
out("  data jsonb not null,");
out("  created_at timestamptz not null default now(),");
out("  updated_at timestamptz not null default now()");
out(");");
out();
out("create table if not exists customer_notes (");
out("  id text primary key,");
out("  company_id text not null default 'air-king',");
out("  customer_id text not null,");
out("  text text not null,");
out("  author text not null,");
out("  date text not null,");
out("  created_at timestamptz not null default now()");
out(");");
out("create index if not exists idx_notes_customer on customer_notes(customer_id);");
out();
out("create table if not exists customer_photos (");
out("  id text primary key,");
out("  company_id text not null default 'air-king',");
out("  customer_id text not null,");
out("  data_url text not null,");
out("  file_name text not null,");
out("  uploaded_at text not null,");
out("  analysis text,");
out("  created_at timestamptz not null default now()");
out(");");
out("create index if not exists idx_photos_customer on customer_photos(customer_id);");
out();
out("create table if not exists work_orders (");
out("  id text primary key,");
out("  company_id text not null default 'air-king',");
out("  customer_id text not null,");
out("  data jsonb not null,");
out("  created_at timestamptz not null default now(),");
out("  updated_at timestamptz not null default now()");
out(");");
out("create index if not exists idx_wo_customer on work_orders(customer_id);");
out();
out("create table if not exists invoices (");
out("  id text primary key,");
out("  company_id text not null default 'air-king',");
out("  customer_id text not null,");
out("  data jsonb not null,");
out("  created_at timestamptz not null default now(),");
out("  updated_at timestamptz not null default now()");
out(");");
out("create index if not exists idx_inv_customer on invoices(customer_id);");
out();
out("create table if not exists quotes (");
out("  id text primary key,");
out("  company_id text not null default 'air-king',");
out("  customer_id text not null,");
out("  data jsonb not null,");
out("  created_at timestamptz not null default now(),");
out("  updated_at timestamptz not null default now()");
out(");");
out("create index if not exists idx_quotes_customer on quotes(customer_id);");
out();
out("create table if not exists memberships (");
out("  id text primary key,");
out("  company_id text not null default 'air-king',");
out("  customer_id text not null,");
out("  data jsonb not null,");
out("  created_at timestamptz not null default now(),");
out("  updated_at timestamptz not null default now()");
out(");");
out("create index if not exists idx_mem_customer on memberships(customer_id);");
out();

out("-- ---------- ROW LEVEL SECURITY ----------");
out("-- Phase 1: permissive policies for staging/demo with synthetic data.");
out("-- Replace with authenticated per-user policies in Phase 2.");
out();
const tables = [
  "customers",
  "customer_notes",
  "customer_photos",
  "work_orders",
  "invoices",
  "quotes",
  "memberships",
];
for (const t of tables) {
  out(`alter table ${t} enable row level security;`);
  out(`drop policy if exists phase1_public_read on ${t};`);
  out(`create policy phase1_public_read on ${t} for select using (true);`);
  out(`drop policy if exists phase1_public_insert on ${t};`);
  out(`create policy phase1_public_insert on ${t} for insert with check (true);`);
  out(`drop policy if exists phase1_public_update on ${t};`);
  out(`create policy phase1_public_update on ${t} for update using (true) with check (true);`);
  out();
}
out("comment on table customers is 'Phase 1 permissive RLS — replace in Phase 2 with auth-based policies.';");
out();

out("-- ---------- SEED DATA ----------");
out("-- Synthetic test data from mock-data.ts. Safe to re-run (upsert).");
out();

// Helper to upsert a jsonb-blob row
function upsertBlob(table: string, id: string, customerId: string, obj: unknown) {
  out(
    `insert into ${table} (id, company_id, customer_id, data) values (${sqlStr(id)}, 'air-king', ${sqlStr(
      customerId
    )}, ${jsonb(obj)}) on conflict (id) do update set data = excluded.data, updated_at = now();`
  );
}

out("-- customers");
for (const c of customers) {
  // store full customer object as the jsonb blob (includes id, contacts, properties, etc.)
  upsertBlob("customers", c.id, c.id, c);
}
out();

out("-- quotes");
for (const q of quotes) {
  upsertBlob("quotes", q.id, q.customerId, q);
}
out();

out("-- work_orders");
for (const w of workOrders) {
  upsertBlob("work_orders", w.id, w.customerId, w);
}
out();

out("-- invoices");
for (const inv of invoices) {
  upsertBlob("invoices", inv.id, inv.customerId, inv);
}
out();

out("-- memberships");
for (const m of memberships) {
  upsertBlob("memberships", m.id, m.customerId, m);
}
out();

out("-- ---------- DONE ----------");
out("select 'customers: ' || count(*) from customers");
out("union all select 'quotes: ' || count(*) from quotes");
out("union all select 'work_orders: ' || count(*) from work_orders");
out("union all select 'invoices: ' || count(*) from invoices");
out("union all select 'memberships: ' || count(*) from memberships;");

const fs = await import("fs");
const target = "/home/user/workspace/air-king-crm/supabase/001_initial_schema_and_seed.sql";
fs.mkdirSync("/home/user/workspace/air-king-crm/supabase", { recursive: true });
fs.writeFileSync(target, lines.join("\n") + "\n");
console.log("Wrote", target, "(" + lines.length + " lines)");
