import { useEffect, useRef, useState } from "react";
import { crm } from "@/lib/crm-api";
import { useAuth } from "@/context/auth-context";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { checklistSchema, completionErrors, templates, results, type Checklist } from "../../../shared/crown-checklists";

export function CrownChecklists({id,onClose}:{id:string;onClose:()=>void}){
 const {profile}=useAuth();const [data,setData]=useState<any>(null),[report,setReport]=useState<Checklist|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);const lock=useRef(false);
 useEffect(()=>{let active=true;crm(`crm/memberships/${encodeURIComponent(id)}`).then(r=>{if(active)setData(r);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[id]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue="";}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
 const discard=()=>!dirty||window.confirm("Discard unsaved checklist changes?");
 const change=(patch:Partial<Checklist>)=>{setReport(r=>r?{...r,...patch}:r);setDirty(true);};
 const start=(e:any,unit:number,kind:Checklist["kind"])=>{if(!discard())return;setError("");setDirty(true);setReport({id:crypto.randomUUID(),kind,equipmentId:e.id,unit,date:new Date().toLocaleDateString("en-CA"),technician:profile?.full_name||"",equipmentLabel:`${e.type}: ${e.description||"Covered equipment"} — unit ${unit}`,modelSerial:"",filter:[e.filterSize,e.filterQuantity?`quantity ${e.filterQuantity}`:"",e.filterNotes].filter(Boolean).join("; "),stage:"",manual:"",answers:{},readings:{},work:"",followUp:"",finalCondition:"",restored:false,status:"draft"});};
 const save=async(status:Checklist["status"])=>{if(!report||lock.current)return;setError("");const parsed=checklistSchema.safeParse({...report,status});if(!parsed.success){setError(parsed.error.issues[0].message);return;}const c=parsed.data;if(status==="completed"){const issues=completionErrors(c);if(issues.length){setError(issues.slice(0,4).join(" ")+(issues.length>4?` (${issues.length-4} more fields need attention.)`:""));return;}}
 lock.current=true;setBusy(true);try{const next=await crm(`crm/memberships/${encodeURIComponent(id)}/checklists`,"POST",{version:data.version,checklist:c});setData(next);setReport(c);setDirty(false);window.dispatchEvent(new Event("crm-refresh"));}catch(e:any){setError(e.message);}finally{lock.current=false;setBusy(false);}};
 const t=report?templates[report.kind]:null,readOnly=report?.status==="completed";
 function download(){if(!report||!t)return;const esc=(s:unknown)=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));const row=(a:string,b:unknown)=>`<tr><th>${esc(a)}</th><td>${esc(b)}</td></tr>`;const html=`<!doctype html><meta charset="utf-8"><title>Crown Care report</title><style>body{font:14px Arial;margin:32px;color:#12304a}table{border-collapse:collapse;width:100%}td,th{border:1px solid #bbc;padding:8px;text-align:left;white-space:pre-wrap}tr{break-inside:avoid}h2{margin-top:24px}@media print{body{margin:12px}}</style><h1>Air King Crown Care — ${esc(t.title)}</h1><p>${esc(data.membership.customerName)} · ${esc(data.membership.propertyAddress)}</p><p>${esc(report.equipmentLabel)} · ${esc(report.date)} · ${esc(report.status)}</p><table>${[["Report ID",report.id],["Technician",report.technician],["Model / serial",report.modelSerial],["Filter",report.filter],["Stage / speed",report.stage],["Manual / targets",report.manual]].map(([a,b])=>row(a,b)).join("")}</table><h2>Inspections</h2><table>${t.tasks.map((task,i)=>row(task,(report.answers[i]?.result||"Not entered")+"\n"+(report.answers[i]?.note||""))).join("")}</table><h2>Readings</h2><table>${t.readings.map(k=>row(k,report.readings[k]||"Not entered")).join("")}</table><h2>Closeout</h2><table>${row("Work performed",report.work)+row("Follow-up / customer notification",report.followUp)+row("Final condition",report.finalCondition)+row("Panels / thermostat / work area confirmed",report.restored?"Yes":"No")}</table>`;const url=URL.createObjectURL(new Blob([html],{type:"text/html"}));const a=document.createElement("a");a.href=url;a.download=`Crown-Care-${report.kind}-${report.date}-${report.id}.html`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
 const field=(key:keyof Checklist,label:string,type="text")=><label className="block text-sm space-y-1">{label}<Input type={type} value={String(report?.[key]??"")} onChange={e=>change({[key]:e.target.value})}/></label>;
 const returnTemp=Number(report?.readings["Return temperature (°F)"]),supplyTemp=Number(report?.readings["Supply temperature (°F)"]);const hasTemps=!!report?.readings["Return temperature (°F)"]?.trim()&&!!report?.readings["Supply temperature (°F)"]?.trim()&&Number.isFinite(returnTemp)&&Number.isFinite(supplyTemp);
 return <Dialog open onOpenChange={v=>{if(!v&&!busy&&discard())onClose();}}><DialogContent className="max-w-4xl max-h-[92dvh] overflow-y-auto w-[calc(100%-1rem)]"><DialogHeader><DialogTitle>Crown Care checklists{data?` — ${data.membership.customerName}`:""}</DialogTitle><DialogDescription>One report per covered unit and visit. Save drafts as you work; completed reports remain read-only.</DialogDescription></DialogHeader>
 {error&&<p role="alert" className="text-destructive border border-destructive rounded p-3">{error}</p>}
 {!data&&!error&&<p>Loading membership…</p>}
 {data&&!report&&<div className="space-y-4"><h3 className="font-semibold">Start a checklist</h3>{!data.membership.coveredEquipment?.length&&<p>Use Edit Coverage & Price to add the covered equipment first.</p>}{data.membership.coveredEquipment?.map((e:any)=><div key={e.id} className="border rounded p-3 space-y-2"><p className="font-medium">{e.type} {e.description}</p><p className="text-sm">Filter: {e.filterSize||"Not recorded"} {e.filterNotes}</p>{Array.from({length:e.quantity},(_,i)=><div key={i} className="flex flex-wrap gap-2 items-center"><span>Unit {i+1}</span><Button size="sm" variant="outline" onClick={()=>start(e,i+1,"furnace")}>Furnace checklist</Button><Button size="sm" variant="outline" onClick={()=>start(e,i+1,"ac")}>AC checklist</Button></div>)}</div>)}<h3 className="font-semibold">Saved reports</h3>{!(data.membership.checklists||[]).length&&<p>No checklists saved yet.</p>}{[...(data.membership.checklists||[])].reverse().map((r:any)=><Button key={r.id} className="w-full h-auto whitespace-normal justify-start text-left" variant="outline" onClick={()=>{setReport(checklistSchema.parse(Object.fromEntries(Object.keys(checklistSchema.shape).map(k=>[k,r[k]]))));setDirty(false);setError("");}}>{r.date} · {templates[r.kind as Checklist["kind"]].title} · {r.equipmentLabel} · {r.status}</Button>)}</div>}
 {report&&t&&<div className="space-y-5"><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={()=>{if(discard()){setReport(null);setDirty(false);setError("");}}}>Back to reports</Button><Button variant="outline" onClick={download}>Download printable report</Button><span className="text-sm self-center">{dirty?"Unsaved changes":readOnly?"Completed report":"Saved draft"}</span></div><h3 className="font-semibold">{t.title} — {report.equipmentLabel}</h3><p className="text-sm text-muted-foreground">{t.scope} Follow the company safety procedure for unsafe conditions. Do not bypass safety controls.</p>
 <fieldset disabled={busy||readOnly} className="space-y-5"><div className="grid sm:grid-cols-2 gap-3">{field("date","Visit date","date")}{field("technician","Technician sign-off name")}{field("modelSerial","Manufacturer / model / serial")}{field("filter","Filter size / quantity / notes")}{field("stage","Tested stage or speed")}{field("manual","Manual reference / applicable manufacturer targets")}</div>
 <section className="space-y-3"><h3 className="font-semibold">1. Inspect and service</h3>{t.tasks.map((task,i)=>{const a=report.answers[i]||{note:""};return <div key={i} className="border rounded p-3 space-y-2"><p className="font-medium text-sm">{i+1}. {task}</p><div role="radiogroup" aria-label={task} className="flex flex-wrap gap-3">{results.map(r=><label key={r} className="flex items-center gap-1.5 text-sm"><input type="radio" name={`inspection-${report.id}-${i}`} checked={a.result===r} onChange={()=>change({answers:{...report.answers,[i]:{...a,result:r}}})}/>{r}</label>)}</div><Textarea aria-label={`Inspection ${i+1} notes`} placeholder={a.result&&a.result!=="OK"?"Required: explain finding, action or why not tested / applicable":"Notes / work performed / inspection limitations"} value={a.note} onChange={e=>change({answers:{...report.answers,[i]:{...a,note:e.target.value}}})}/></div>;})}</section>
 <section className="space-y-3"><h3 className="font-semibold">2. Operating readings</h3><p className="text-sm text-muted-foreground">Compare with this equipment's manual. Enter a value, or “N/A — reason” / “Not tested — reason”. Record limits in the manual/targets field. No universal pressure or temperature pass limits.</p>{hasTemps&&<p className="rounded bg-muted p-3">{report.kind==="furnace"?"Temperature rise":"Cooling temperature split"}: {(report.kind==="furnace"?supplyTemp-returnTemp:returnTemp-supplyTemp).toFixed(1)} °F — compare with the equipment requirements.</p>}<div className="grid sm:grid-cols-2 gap-3">{t.readings.map(k=><label key={k} className="text-sm space-y-1">{k}<Input value={report.readings[k]||""} onChange={e=>change({readings:{...report.readings,[k]:e.target.value}})}/></label>)}</div></section>
 <section className="space-y-3"><h3 className="font-semibold">3. Closeout</h3><label className="block text-sm">Work performed / before and after readings / report or photo references<Textarea value={report.work} onChange={e=>change({work:e.target.value})}/></label><label className="block text-sm">Repairs / customer and supervisor notification / follow-up date<Textarea value={report.followUp} onChange={e=>change({followUp:e.target.value})}/></label><label className="block text-sm">Final condition<select className="block border rounded p-2 bg-background w-full" value={report.finalCondition} onChange={e=>change({finalCondition:e.target.value as Checklist["finalCondition"]})}><option value="">Choose condition</option>{["Operating","Needs attention","Shut down"].map(v=><option key={v}>{v}</option>)}</select></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={report.restored} onChange={e=>change({restored:e.target.checked})}/>Panels secured, thermostat addressed for final condition, and work area cleaned.</label></section></fieldset>
 {!readOnly&&<div className="flex flex-wrap gap-2 border-t pt-3"><Button variant="outline" disabled={busy} onClick={()=>save("draft")}>{busy?"Saving…":"Save draft"}</Button><Button disabled={busy} onClick={()=>{if(window.confirm("Sign and complete this report? Completed reports cannot be edited."))save("completed");}}>Sign & complete</Button></div>}</div>}
 </DialogContent></Dialog>;
}
